-- =============================================================================
--  DI LOLLO RUNNER — leaderboard en Supabase
--  Pasos: Supabase > SQL Editor > New query > pegá esto > Run
-- =============================================================================

-- 1) Tabla de puntajes ------------------------------------------------------
create table if not exists public.leaderboard (
  id          bigint generated by default as identity primary key,
  name        text        not null,
  score       integer     not null default 0,
  dist        integer     not null default 0,
  cigarettes  integer     not null default 0,
  duration    real        not null default 0,
  created_at  timestamptz not null default now(),
  constraint name_largo check (char_length(name) between 1 and 16),
  constraint score_positivo check (score >= 0)
);

create index if not exists leaderboard_score_idx
  on public.leaderboard (score desc);

-- 2) Seguridad: anybody puede LEER, pero NADIE escribe directo ---------------
alter table public.leaderboard enable row level security;

drop policy if exists "lectura publica" on public.leaderboard;
create policy "lectura publica"
  on public.leaderboard
  for select
  using (true);

-- OJO: no creamos ninguna policy de insert/update/delete a propósito.
-- Sin esas policies, el navegador no puede insertar ni borrar nada:
-- la única vía de escritura es la función de abajo.

-- 3) Función de envío, con validación anti-trampa --------------------------
create or replace function public.submit_score(
  p_name        text,
  p_score       integer,
  p_dist        integer,
  p_cigarettes  integer,
  p_duration    real
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_clean   text;
  v_max     integer;
  v_min_t   real;
  v_rank    integer;
  v_nombre  text;
begin
  -- Saneamos el nombre: solo letras, números, espacio, guion y guion bajo.
  v_clean := left(
    regexp_replace(coalesce(p_name, ''), '[^a-zA-Z0-9 _\-]', '', 'g'),
    16
  );
  if length(trim(v_clean)) = 0 then
    v_clean := 'Jugador';
  end if;

  -- Chequeos básicos
  if p_score is null or p_score < 0 then
    raise exception 'score invalido';
  end if;

  -- No se puede recorrer más rápido que la velocidad máxima del juego.
  -- La distancia en metros se suma a velocidad * dt * 0.55,
  -- con velocidad tope de 30 => 16.5 m/s. Dejamos margen hasta 14.
  v_min_t := greatest(coalesce(p_dist, 0) / 14.0, 3.0);
  if coalesce(p_duration, 0) < v_min_t then
    raise exception 'duracion imposible';
  end if;

  -- Techo de puntaje plausible para esa distancia y esa cantidad de cigarrillos.
  v_max := 800 + coalesce(p_dist, 0) * 50 + coalesce(p_cigarettes, 0) * 150;
  if p_score > v_max then
    raise exception 'score no plausible';
  end if;

  insert into public.leaderboard (name, score, dist, cigarettes, duration)
  values (v_clean, p_score, coalesce(p_dist, 0), coalesce(p_cigarettes, 0), coalesce(p_duration, 0));

  -- Posición en el ranking
  select count(*) + 1 into v_rank
  from public.leaderboard l
  where l.score > p_score;

  return jsonb_build_object('ok', true, 'rank', v_rank, 'name', v_clean);
end;
$$;

grant execute on function public.submit_score(text, integer, integer, integer, real)
  to anon, authenticated;

-- 4) Vista cómoda para el ranking ------------------------------------------
drop view if exists public.top_scores;
create view public.top_scores
  as
  select
    row_number() over (order by score desc, created_at asc) as rank,
    name,
    score,
    dist,
    cigarettes,
    created_at
  from public.leaderboard
  order by score desc, created_at asc;

grant select on public.top_scores to anon, authenticated;

-- =============================================================================
--  Verificación (opcional): probá desde el SQL Editor
--  select * from public.submit_score('Prueba', 1234, 300, 40, 30);
--  select * from public.top_scores limit 10;
-- =============================================================================